language: node_js
sudo: false
node_js:
  "node"

notifications:
  email:
    recipients:
      - foobarcpen321@gmail.com
    on_success: always
    on_failure: always

branches:
  only:
  - master
  - ci_test

after_success:
- npm run coveralls