language: node_js
sudo: false
node_js:
  "node"

notifications:
  email:
    recipients:
      - foobarcpen321@gmail.com
    on_success: never # default: always
    on_failure: always # default: always